package net.balacobaco.cpmcore.utils;

import java.util.ArrayList;
import java.util.List;

public class HelderFalas {
    List<String> frases = new ArrayList<>();
    public HelderFalas(){
        frases.add("Vocês sabem por que estão aqui.");
        frases.add("Vocês estudam no colégio da polícia militar de pernambuco, devem seguir o padrão CPM!");
        frases.add("Vocês ficam vindo com o uniforme alterado!");
        frases.add("Não venham alterados!");
        frases.add("Vocês estão com o cabelo errado! Barba mal feita!");
        frases.add("O corte de cabelo precisa estar de acordo com as normas!");
        frases.add("Não permitimos cortes de cabelo fora do regulamento!");
        frases.add("Vocês sabem as regras de apresentação pessoal!");
        frases.add("Os uniformes devem estar impecáveis!");
        frases.add("A disciplina começa pelo visual!");
        frases.add("Não aceitamos desculpas para uniformes desleixados!");
        frases.add("A barba deve ser bem feita todos os dias!");
        frases.add("O colégio exige padronização completa!");
        frases.add("A farda deve ser usada corretamente!");
        frases.add("Vocês representam a instituição, comportem-se à altura!");
        frases.add("O cumprimento das regras é obrigatório!");
        frases.add("Aparência pessoal é uma questão de respeito!");
        frases.add("Vocês devem servir de exemplo para outros alunos!");
        frases.add("O cabelo não pode ultrapassar o limite permitido!");
        frases.add("Não aceitamos alunos com uniforme sujo ou rasgado!");
        frases.add("A higiene pessoal é fundamental!");
        frases.add("A apresentação impecável é uma questão de honra!");
        frases.add("Vocês são futuros policiais, mantenham-se à altura!");
        frases.add("O fardamento correto é um sinal de disciplina!");
        frases.add("Não toleramos relaxamento nas normas de vestimenta!");
        frases.add("O padrão CPM deve ser seguido à risca!");
        frases.add("Vocês devem estar sempre apresentáveis!");
        frases.add("A primeira impressão é a que fica!");
        frases.add("Uniforme completo e bem cuidado é obrigatório!");
        frases.add("Vocês devem estar prontos para qualquer inspeção!");
        frases.add("A disciplina reflete-se no uniforme!");
        frases.add("Aparência desleixada não é permitida!");
        frases.add("Vocês sabem o que se espera de vocês!");
        frases.add("O uniforme é um símbolo de respeito!");
        frases.add("Cabelos longos são inaceitáveis!");
        frases.add("Cada detalhe do uniforme é importante!");
        frases.add("Vocês são a imagem do colégio militar!");
        frases.add("A disciplina começa com vocês!");
        frases.add("O fardamento correto mostra compromisso!");
        frases.add("Vocês devem estar impecáveis todos os dias!");
        frases.add("O corte de cabelo deve ser padronizado!");
        frases.add("A barba precisa estar sempre feita!");
        frases.add("O uniforme deve estar limpo e passado!");
        frases.add("Vocês devem seguir as normas com rigor!");
        frases.add("O colégio exige excelência em tudo!");
        frases.add("Vocês representam o CPM de Pernambuco!");
        frases.add("O cuidado com a aparência é essencial!");
        frases.add("Vocês devem se apresentar com dignidade!");
        frases.add("O uniforme é a identidade de vocês!");
        frases.add("Não aceitamos desvios das normas estabelecidas!");
        frases.add("O compromisso com a disciplina é constante!");
        frases.add("Vocês devem estar prontos para servir!");
        frases.add("A apresentação pessoal deve ser exemplar!");
        frases.add("A farda deve ser motivo de orgulho!");
        frases.add("Vocês são futuros líderes, comportem-se como tal!");
        frases.add("A disciplina é refletida na aparência!");
        frases.add("Não toleramos desleixo com o uniforme!");
        frases.add("Vocês devem manter o padrão elevado!");
        frases.add("O uniforme representa a honra da instituição!");
        frases.add("Cabelos compridos não são permitidos!");
        frases.add("Vocês devem estar sempre bem cuidados!");
        frases.add("A higiene é parte fundamental da disciplina!");
        frases.add("A apresentação correta é indispensável!");
        frases.add("Vocês sabem as regras, sigam-nas!");
        frases.add("O cuidado com a aparência é mandatório!");
        frases.add("O colégio exige a máxima disciplina!");
        frases.add("Vocês devem estar sempre impecáveis!");
        frases.add("A farda é símbolo de responsabilidade!");
        frases.add("O padrão CPM deve ser seguido rigorosamente!");
        frases.add("A apresentação impecável é obrigatória!");
        frases.add("Vocês devem manter a dignidade no vestir!");
        frases.add("O corte de cabelo deve estar conforme as normas!");
        frases.add("Vocês precisam representar bem a instituição!");
        frases.add("O uniforme deve estar sempre em boas condições!");
        frases.add("A disciplina começa pela aparência!");
        frases.add("Não aceitamos uniformes desleixados!");
        frases.add("Vocês sabem a importância do uniforme!");
        frases.add("A apresentação pessoal deve ser impecável!");
        frases.add("O fardamento correto é um dever!");
        frases.add("Vocês devem estar sempre prontos!");
        frases.add("A aparência reflete a disciplina interna!");
        frases.add("O uniforme é um símbolo de compromisso!");
        frases.add("Vocês devem seguir o regulamento à risca!");
        frases.add("A apresentação correta é fundamental!");
        frases.add("Vocês sabem o que é esperado de vocês!");
        frases.add("O padrão CPM é inegociável!");
        frases.add("O corte de cabelo deve ser adequado!");
        frases.add("A barba deve ser feita diariamente!");
        frases.add("Vocês devem manter o uniforme em perfeitas condições!");
        frases.add("A disciplina começa pelo visual de vocês!");
        frases.add("Não aceitamos relaxamento na aparência!");
        frases.add("Vocês representam o CPM, comportem-se!");
        frases.add("O uniforme é parte da identidade de vocês!");
        frases.add("Vocês devem estar sempre apresentáveis!");
        frases.add("A apresentação pessoal é crucial!");
        frases.add("O uniforme deve estar sempre impecável!");
        frases.add("A disciplina é refletida na aparência de vocês!");
        frases.add("Vocês devem manter a honra da instituição!");
        frases.add("O cuidado com o uniforme é essencial!");
        frases.add("Vocês sabem o que se espera, sigam o padrão!");
    }

    public List<String> getFrases() {
        return frases;
    }
}
